analyzeCommits:
  releaseRules:
    - type: build
      release: patch
branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - labels: false
      releasedLabels: false
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: |-
        # Changelog

        All notable changes to this project will be documented in this file.
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
      message: |-
        chore(release): v${nextRelease.version} [skip ci]

        ${nextRelease.notes}
  - - "@semantic-release/exec"
    - publishCmd: |
        set -e

        IMAGE_NAME='ghcr.io/maxbrunet/prometheus-elasticache-sd'
        IMAGE_TAG='v${nextRelease.version}'

        podman build \
          --platform linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
          --manifest "$IMAGE_NAME:$IMAGE_TAG" .

        podman manifest push "$IMAGE_NAME:$IMAGE_TAG" "docker://$IMAGE_NAME:$IMAGE_TAG"
        podman manifest push "$IMAGE_NAME:$IMAGE_TAG" "docker://$IMAGE_NAME:latest"
preset: conventionalcommits
presetConfig:
  types:
    - type: feat
      section: Features
    - type: feature
      section: Features
    - type: fix
      section: Bug Fixes
    - type: perf
      section: Performance Improvements
    - type: revert
      section: Reverts
    - type: docs
      section: Documentation
    - type: style
      section: Styles
    - type: chore
      section: Miscellaneous Chores
    - type: refactor
      section: Code Refactoring
    - type: test
      section: Tests
    - type: build
      section: Build System
    - type: ci
      section: Continuous Integration
